DEV: Add linting and CI tests
discourse/discourse-zoom pull request #27
Opened 2021-08-18 17:45 UTC by jmperez127

2021-08-19 11:46 UTC, CvX requested changes

2021-08-19 11:46 UTC, CvX commented on assets/javascripts/discourse/controllers/webinar-picker.js.es6
> +  pastWebinarDisabled() {
This depends on those two properties. The fix would be to use those function args instead. 🙂

2021-08-19 11:46 UTC, CvX commented on app/controllers/webinars_controller.rb
> +        nil
Those two `nil` values are not necessary

2021-08-19 11:46 UTC, CvX commented on assets/javascripts/discourse/components/webinar-register.js.es6
> +  canUnregister(starts_at) {
This should declare dependency on `isAttendee` and `registered`. The same applies to `userCanRegister()` below.

2021-09-15 17:11 UTC, pmusaraj commented
Specs are fixed here now @jmperez127, I'll let you address CvX's comments.

2021-11-26 00:27 UTC, CvX approved these changes
I fixed issues mentioned in my comments, and updated files from the plugin skeleton. Merging!

2021-11-26 00:27 UTC, merged